steps:
  tmsUpload:
    credentialsId: TMSCredPRDID
    nodeName: dev-hr-mfa
    mtaPath: temp/hr_cf_w4.mtar
    customDescription: HR W4 module
    verbose: true
    cloudFoundry/org: dev-cf-valvoline-mfa
    cloudFoundry/space: dev-hr-mfa
    collectTelemetryData: false